### ISSUE TITLE
Authenication via VK / Google

### ISSUE THREAD

**Issue by AlekseiIvshin** [AlekseiIvshin/CatchTheAsteroid#5]

**Comment by VladislavDan** [comment]
For working google authorization you should use your own google-service.json that you can generate it in https://developers.google.com/mobile/add?platform=android&cntapi=analytics&cnturl=https%3A%2F%2Fdevelopers.google.com%2Fanalytics%2Fdevguides%2Fcollection%2Fandroid%2Fv4%2Fapp%3Fconfigured%3Dtrue&cntlbl=Continue+Adding+Analytics&hl=ru. Please replace my google-service.json on yours. It work so because google-service.json generated using sha key our debug or release keys.

**Comment by VladislavDan** [comment]
For google authorization I used https://www.npmjs.com/package/react-native-google-sign-in 
For VK authorization I used https://www.npmjs.com/package/react-native-vkontakte-login

**Comment by VladislavDan** [comment]
For working VK authorization in Android you need to make app with your SHA using this instruction https://vk.com/editapp?act=create Please find and replace all my VK_ID in android app and RN code. src/containers/LoginScreen.js and android/app/src/main/res/values/strings.xml

**Comment by VladislavDan** [comment]
Please do not use react-native run-ios for building ios application. Use only XCode.

**Comment by AlekseiIvshin** [comment]
Thank you! Done!
